import { execAsync } from "./metrics"
import GLib from "gi://GLib?version=2.0"
import Gio from "gi://Gio?version=2.0"
import Config from "../config"
import { readFile } from "ags/file"
import { isFile } from "./utils"

// Everything about turning the scss tree into the cached stylesheet,
// with NO dependency on ags/gtk4/app — which runs Gtk.init() at import
// and therefore needs a display.
//
// That split is the point: `scripts/precompile-style.ts` bundles this
// module and runs it headlessly from `wam install` / `wam update`, so a
// cold start has a warm cache and never has to block. `lib/style.ts` is
// the display-side half (applying the result, the request command).
//
// The blocking compile still exists, because it still has to: ags loads
// the css at activation, so on a genuinely cold cache the alternative is
// a shell that starts unstyled and repaints a beat later.

const scssDir = `${Config.instanceSrcDir}/scss`
const themeDir = `${scssDir}/theme`
// generated outside the source tree: the tree is read-only on
// system-wide installs. scss files import it by bare name and sass
// resolves that through the cache dir load path below
const activeThemePath = `${Config.instanceCacheDir}/active-theme.scss`
// the same trick for the handful of tokens that come from the CONFIG
// rather than from a theme: sass cannot read the user's toml, so the
// shell writes them where the load path resolves them by bare name
const activeTuningPath = `${Config.instanceCacheDir}/active-tuning.scss`

// the cache dir is keyed by instance NAME, so checkouts with the same
// dir name (repo + worktrees) share it: css compiled from another
// tree's scss must never be accepted as fresh by this one
const cssSrcMarkerPath = `${Config.instanceCacheDir}/style.src`

function writeCssSrcMarker() {
    try {
        GLib.file_set_contents(cssSrcMarkerPath, scssDir)
    } catch {}
}

// array form: no shell, so a repo path with spaces can't break the
// command. Load paths keep bare-name imports resolving no matter where
// the importing file lives: the cache dir for the generated
// active-theme, the theme dir and the scss dir for user styles
function sassArgs(): string[] {
    return [
        "sass",
        "--load-path",
        Config.instanceCacheDir,
        "--load-path",
        themeDir,
        "--load-path",
        scssDir,
        Config.scssPath,
        Config.cssPath,
    ]
}

// the configured theme is what scss files import as active-theme.
// Returns true when the copy changed: a theme switch in the config
// touches no scss mtime, so the freshness sweep alone would miss it
export function syncActiveTheme(): boolean {
    // the shell creates this in app.tsx before it ever compiles, but
    // this module also runs standalone (scripts/precompile-style.ts),
    // where nothing has yet — and the copy below throws on a missing
    // parent rather than creating one
    try {
        GLib.mkdir_with_parents(Config.instanceCacheDir, 0o755)
    } catch (e) {
        console.warn("style: could not create the cache dir:", e)
    }
    const srcPath = `${themeDir}/${Config.theme}.scss`
    try {
        if (readFile(activeThemePath) === readFile(srcPath)) return false
    } catch {
        /* missing or unreadable copy → (re)generate it */
    }
    Gio.File.new_for_path(srcPath).copy(
        Gio.File.new_for_path(activeThemePath),
        Gio.FileCopyFlags.OVERWRITE,
        null,
        null,
    )
    return true
}

/**
 * Write the config-derived scss tokens (`scss/conf.scss` @uses these).
 *
 * Returns true when the contents changed, for the same reason
 * `syncActiveTheme` does: changing `density` in the config touches no
 * scss mtime, so the freshness sweep on its own would go on serving a
 * stylesheet built at the old spacing.
 */
export function syncTuning(): boolean {
    const body =
        "// Generated by wam-shell from config.toml — do not edit; every\n" +
        "// compile overwrites it. See lib/styleCompile.ts.\n" +
        `$density: ${Config.appearance.density};\n` +
        `$bar-float-margin: ${Config.barFloatMargin}px;\n`
    try {
        if (readFile(activeTuningPath) === body) return false
    } catch {
        /* missing or unreadable → (re)generate it */
    }
    try {
        GLib.file_set_contents(activeTuningPath, body)
    } catch (e) {
        // nothing to fall back on: conf.scss imports this by bare name,
        // so a failure here is a failure to compile at all. Say which.
        console.error("style: could not write active-tuning.scss:", e)
    }
    return true
}

// user.scss holds personal overrides (gitignored, created if missing).
// Returns the path in use: the tree, or the cache-dir fallback on
// read-only installs
export function ensureUserScss(): string {
    const path = `${scssDir}/user.scss`
    if (isFile(path)) return path
    try {
        GLib.file_set_contents(path, "")
        return path
    } catch {
        // read-only source tree: an empty file in the cache dir still
        // satisfies the `@use "user.scss"` through the load path
        const fallback = `${Config.instanceCacheDir}/user.scss`
        try {
            GLib.file_set_contents(fallback, "")
        } catch {}
        return fallback
    }
}

function mtimeUsec(info: Gio.FileInfo): number {
    return (
        info.get_attribute_uint64("time::modified") * 1e6 +
        info.get_attribute_uint32("time::modified-usec")
    )
}

// newest mtime anywhere under dir, dir mtimes included (a copied-in
// file may keep an old mtime; its parent dir's can't). Unreadable dirs
// return Infinity so the freshness check errs on recompiling
function newestMtime(dir: string): number {
    try {
        const f = Gio.File.new_for_path(dir)
        let newest = mtimeUsec(
            f.query_info("time::modified,time::modified-usec", Gio.FileQueryInfoFlags.NONE, null),
        )
        const en = f.enumerate_children(
            "standard::name,standard::type,time::modified,time::modified-usec",
            Gio.FileQueryInfoFlags.NONE,
            null,
        )
        let info: Gio.FileInfo | null
        while ((info = en.next_file(null)) !== null) {
            const m =
                info.get_file_type() === Gio.FileType.DIRECTORY
                    ? newestMtime(`${dir}/${info.get_name()}`)
                    : mtimeUsec(info)
            if (m > newest) newest = m
        }
        return newest
    } catch {
        return Infinity
    }
}

export function cssIsFresh(userScss: string): boolean {
    try {
        if (readFile(cssSrcMarkerPath) !== scssDir) return false
        const fileUsec = (path: string) =>
            mtimeUsec(
                Gio.File.new_for_path(path).query_info(
                    "time::modified,time::modified-usec",
                    Gio.FileQueryInfoFlags.NONE,
                    null,
                ),
            )
        const cssMtime = fileUsec(Config.cssPath)
        // the marker is written right after every successful compile, so
        // css newer than the marker came from a compile this tree didn't
        // do (a checkout without the marker logic, e.g. a worktree)
        if (cssMtime > fileUsec(cssSrcMarkerPath)) return false
        let newest = newestMtime(scssDir)
        // a fallback user.scss lives outside the tree the sweep covers
        if (userScss.startsWith(Config.instanceCacheDir)) {
            newest = Math.max(
                newest,
                mtimeUsec(
                    Gio.File.new_for_path(userScss).query_info(
                        "time::modified,time::modified-usec",
                        Gio.FileQueryInfoFlags.NONE,
                        null,
                    ),
                ),
            )
        }
        return newest <= cssMtime
    } catch {
        return false
    }
}

/** is dart-sass on PATH at all? The difference between "your scss is
 *  broken" and "the compiler is missing", which the caller reports
 *  differently because the fixes are nothing alike. */
export function sassAvailable(): boolean {
    return GLib.find_program_in_path("sass") !== null
}

/** blocking compile. Returns false when sass could not be run at all. */
export function compileSync(): boolean {
    try {
        const proc = Gio.Subprocess.new(sassArgs(), Gio.SubprocessFlags.NONE)
        proc.wait(null)
        if (!proc.get_successful()) return false
        writeCssSrcMarker()
        return true
    } catch (e) {
        console.error("Failed to compile styles:", e)
        return false
    }
}

/** non-blocking compile; resolves once the marker is written */
export async function compileAsync(): Promise<void> {
    await execAsync(sassArgs())
    writeCssSrcMarker()
}

/**
 * Prepare the cache dir and say whether a compile is actually needed.
 *
 * `cold` distinguishes the two cases that matter to the caller: no css
 * at all (the shell would start unstyled, so it has to block) from a
 * stale one (the previous sheet is fine to show while sass catches up).
 */
export function planCompile(): { needed: boolean; cold: boolean; userScss: string } {
    const themeChanged = syncActiveTheme()
    const tuningChanged = syncTuning()
    const userScss = ensureUserScss()
    const haveCss = isFile(Config.cssPath)
    // sass is the slowest part of startup; when no input is newer than
    // the emitted css, the cached file is reused as-is
    const needed = themeChanged || tuningChanged || !haveCss || !cssIsFresh(userScss)
    return { needed, cold: !haveCss, userScss }
}
