// Test entry point. The bundler needs static imports, so every new
// tests/*.test.ts must be registered here.
import "./utils.test"
import "./relTime.test"
import "./feed.test"
import "./notifdPopups.test"
import "./rowData.test"
import "./timerInput.test"
import "./kbLayout.test"
import "./sysstats.test"
import "./trayPinned.test"
import "./config.test"
import "./metrics.test"
import "./atomicWrite.test"
import "./harvestTimeline.test"
import "./gcal.test"
import "./github.test"
import "./youtube.test"
import "./googleAuth.test"
import "./credentials.test"
import "./todoist.test"
import "./protonmail.test"
import "./sleepTimerState.test"
import "./vpn.test"
import { summary } from "./framework"

summary()
import "./bluetooth.test"
