#!/bin/bash

UPDATE_FILE=/tmp/system_updates
if [[ -n "$XDG_RUNTIME_DIR" ]]; then
    UPDATE_FILE=$XDG_RUNTIME_DIR/system_updates
fi

echo Updates listed in "$UPDATE_FILE"

while (true)
do
	# Checkupdates provided by pacman-contrib
	checkupdates 2> /dev/null > $UPDATE_FILE.swap
    yay -Qau 2> /dev/null >> $UPDATE_FILE.swap

    # atomic rename: readers never see a partially written list
    mv $UPDATE_FILE.swap $UPDATE_FILE

	echo "Available packages to update $(cat $UPDATE_FILE 2> /dev/null | wc -l)"
	sleep 3600
done
